using System.Text;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Newtonsoft.Json.Linq;
using SmarthomeAPI.App;
using SmarthomeAPI.App.Components.Heaters;

namespace SmarthomeAPI
{
    /// <summary>
    /// This class is running on application start (autogenerated).
    /// </summary>
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        /// <summary>
        /// Configure services that application uses.
        /// In this case it's Entity framework database context for heaters and MVC.
        /// </summary>
        /// <param name="services"></param>
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<HeaterContext>();
            services.AddMvc();
        }

        /// <summary>
        /// Configure application itself for using https (in case of non-development environment)
        /// and register exception handler for using my own output in case of error.
        /// </summary>
        /// <example>Error example is `{"Code": 500, "Message": "Something went wrong"}`</example>
        /// <param name="app"></param>
        /// <param name="env"></param>
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseExceptionHandler(errorApp =>
            {
                errorApp.Run(async context =>
                {
                    context.Response.StatusCode = 500;
                    context.Response.ContentType = "application/json";

                    var error = context.Features.Get<IExceptionHandlerFeature>();
                    if (error != null)
                    {
                        var ex = error.Error;

                        await context.Response.WriteAsync(JToken.FromObject(new ErrorDto
                        {
                            Code = 500,
                            Message = ex.Message
                        }).ToString(), Encoding.UTF8);
                    }
                });
            });


            app.UseMvc();
        }
    }
}